version: '3.8'

services:
  # PostgreSQL 服务 - 复用现有数据
  postgres:
    image: postgres:13.13
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 添加健康检查
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  # NocoDB 服务 - 数据库可视化和无代码应用平台
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: always
    ports:
      - "8080:8080"
    # 等待 PostgreSQL 服务启动
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # NocoDB 数据库配置 - 通过服务名连接 PostgreSQL
      NC_DB: "pg://postgres:5432?u=root&p=123456&d=nocodb_db"
      # NocoDB 管理员配置
      NC_AUTH_JWT_SECRET: "569a1821-0a93-45e8-87ab-eb857f20a010"
      NC_ADMIN_EMAIL: "admin@example.com"
      NC_ADMIN_PASSWORD: "admin123"
      # 其他配置
      NC_PUBLIC_URL: "http://localhost:8080"
      NC_DISABLE_TELE: "true"
    volumes:
      # 持久化 NocoDB 数据
      - nocodb_data:/usr/app/data
    networks:
      - app_network

  # n8n 服务 - 工作流自动化
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      # 使用原有的 n8n 数据目录
      - ./n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Asia/Shanghai
      - N8N_SECURE_COOKIE=false
    # 等待 PostgreSQL 服务启动
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  # MinIO 服务 - 对象存储
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API 端口
      - "9001:9001"  # Web UI 端口
    volumes:
      # MinIO 数据目录（新建，不保留原有数据）
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: 12345678
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    name: app_network

volumes:
  postgres_data:
    external:
      name: pgsql_postgres_data
  nocodb_data:
    driver: local