version: '3.8'
services:
  mysql:
    image: mysql:5.7.41
    hostname: mysql-5.7
    container_name: mysql-5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - cache:/var/lib/mysql
volumes:
  cache:
    driver: local
