version: '3.8'
services:
  mysql:
    image: mysql:8.0.32
    hostname: mysql-8
    container_name: mysql-8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - cache:/var/lib/mysql
volumes:
  cache:
    driver: local
